update

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -22,14 +22,14 @@ jobs:
           cat test.txt
       
       - name: Push changes
-      run: |
-        git config --global user.name "teebra1"
-        git config --global user.email "teebrakanakdeka@yahoo.com"
-        git add "artifacts"
-        git stash
-        git pull origin main || echo "Couldn't find remote branch"
-        git checkout stash -- .
-        git commit -m "Baseline File push from pipeline"
-        git push origin HEAD:main --force-with-lease
+        run: |
+          git config --global user.name "teebra1"
+          git config --global user.email "teebrakanakdeka@yahoo.com"
+          git add "artifacts"
+          git stash
+          git pull origin main || echo "Couldn't find remote branch"
+          git checkout stash -- .
+          git commit -m "Baseline File push from pipeline"
+          git push origin HEAD:main --force-with-lease
 
       
